### ISSUE TITLE
Error with start

### ISSUE THREAD

**Issue by jimmyr57000** [MarvinMenzerath/HastebinPlus#7]
Hello,

I have error with npm start

Error: 

root@vps167206:/home/hastebin-plus# npm start

> hastebin-plus@0.0.4 start /home/hastebin-plus
> node ./server.js

npm ERR! hastebin-plus@0.0.4 start: `node ./server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hastebin-plus@0.0.4 start script.
npm ERR! This is most likely a problem with the hastebin-plus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls hastebin-plus
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 2.6.32-042stab111.12
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! cwd /home/hastebin-plus
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /home/hastebin-plus/npm-debug.log
npm ERR! not ok code 0
root@vps167206:/home/hastebin-plus#

**Comment by menzerath** [comment]
You may need a current node.js version like v6.x to run HastebinPlus.
Just follow those instructions: https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions
